CREATE TABLE IF NOT EXISTS profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE,
  photo TEXT,
  color TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  profileId INTEGER NOT NULL,
  date INTEGER NOT NULL,
  score INTEGER NOT NULL,
  answers TEXT,
  FOREIGN KEY(profileId) REFERENCES profiles(id) ON DELETE CASCADE
);
