CREATE TABLE IF NOT EXISTS profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  profileId INTEGER,
  date INTEGER,
  score INTEGER,
  FOREIGN KEY(profileId) REFERENCES profiles(id)
);
